### ISSUE TITLE
inserting the script problems

### ISSUE THREAD

**Issue by johjoh367** [HubSpot/jquery-zoomer#1]
Could you be so kind to help me with the script.
I do not know how to call for the right actions which parts need to be within the header what calls do i make within the body. I want it to be able to iframe exterior sites for me, where the whole frame with its content can be shown smaller or bigger using this script.

**Comment by adamschwartz** [comment]
To use jQuery Zoomer, you need to include scripts for jQuery and the jQuery Zoomer plugin (download [here](https://raw.github.com/HubSpot/jquery-zoomer/master/jquery.zoomer.js)) in `head`. Then add a small bit of javascript to initialize the zoomer with your `iframe`.

```
<script>
  $(function(){
    $('iframe').zoomer({ width: 400, height: 400, zoom: 0.5 });
  })
</script>
```

The following is a bare bones example you can copy:

```
<html>
  <head>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js"></script>
    <script src="jquery.zoomer.js"></script>
    <script>
      $(function(){
        $('iframe').zoomer({ width: 618, height: 400, zoom: 0.6 });
      })
    </script>
    <style>
      iframe {
        border: 0px;
      }
      .zoomer-wrapper {
        border: 1px solid #aaa;
      }
    </style>
  </head>
  <body>
    <iframe src="http://example.com"></iframe>
  </body>
</html>
```

In addition, the [website for the project](http://hubspot.github.com/jquery-zoomer/) contains a working [example](https://github.com/HubSpot/jquery-zoomer/blob/gh-pages/index.html).

**Comment by johjoh367** [comment]
thanks for the handout.
Pity though that the frame of the website only gets smaller and not the actual content inside. From the example you have online i thought that that was the case
