### ISSUE TITLE
demo not working

### ISSUE THREAD

**Issue by ikkez** [HubSpot/jquery-zoomer#4]
sorry, but i was unable to test your demo... i tested it in safari, chrome and firefox on mac...
hitting the run button does nothing.

**Comment by adamschwartz** [comment]
Having a hard time to reproduce.

@ikkez Is it possible this is related to Ghostery, same as [HubSpot/Vex #16](https://github.com/HubSpot/vex/issues/16)?

**Comment by ikkez** [comment]
hi adam. sorry for disrupting you with all my annoying false positives ^^ 
to be sure i removed Ghostery now completly. i think i now understand what this plugin does... i think it works fine here, i was just expecting some sort of animation when clicking the run button, which does not happen.. but i see now that it works... the only not working part left is clicking the "here" button to insert text into the iframe... got "Error: Permission denied to access property 'document'" ... i guess it's due to a security setting for javascript... but anyway, the iframe zoomed correctly. cheers

**Comment by zackbloom** [comment]
@adamschwartz That error is the same thing we were getting in pace, you need to switch to using document.write.
